

services:
  web:
    build:
      context: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://chengyan:tan5224539@db:5432/yike?sslmode=disable
    command: >
      sh -c "./wait-for-it.sh db 5432 --
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 classifiedads.wsgi:application"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: chengyan
      POSTGRES_PASSWORD: tan5224539
      POSTGRES_DB: yike
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
