# Generated by Django 5.1.2 on 2024-10-16 10:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_alter_ads_id_alter_adsbottombanner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_tutor', models.TextField()),
                ('about_lesson', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wechat', models.CharField(max_length=200)),
                ('last_time_active', models.DateTimeField(auto_now=True)),
                ('average_response_time', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.author')),
            ],
            options={
                'verbose_name_plural': 'Tutor Ads',
            },
        ),
        migrations.RemoveField(
            model_name='ads',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='state',
        ),
        migrations.DeleteModel(
            name='AdsBottomBanner',
        ),
        migrations.DeleteModel(
            name='AdsRightBanner',
        ),
        migrations.DeleteModel(
            name='AdsTopBanner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.AlterField(
            model_name='adsimages',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.tutorad'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
