# Generated by Django 5.1.2 on 2024-10-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_tutorad_remove_ads_author_remove_ads_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorad',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_ads', to='ads.category'),
        ),
    ]
