# Generated by Django 5.1.2 on 2024-12-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_tutorad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorad',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
